### ISSUE TITLE
Hello, I didn't find the inference model. Is it not released yet? It will be released when the hat is set.

### ISSUE THREAD

**Issue by zhanghongyong123456** [stefanLeong/S2CRNet#3]

**Comment by vinthony** [comment]
Hi, thanks for your attention. I create a new repo for the run-able demos for both image harmonization and video harmonization, https://github.com/vinthony/S2CRNet-demos

**Comment by zhanghongyong123456** [comment]
> Hi, thanks for your attention. I create a new repo for the run-able demos for both image harmonization and video harmonization, https://github.com/vinthony/S2CRNet-demos

I saw the demonstration video of this project, and the web video stream is adopted. Is it possible to achieve real-time for  HD and  4K 
https://github.com/vinthony/S2CRNet-demos#video-harmonization-demo

**Comment by vinthony** [comment]
I think it is possible if you are using a GPU to run and optimize the model via [TensorRT](https://github.com/NVIDIA/TensorRT)
